MasterApeAdmin
ApeSwapFinance/apeswap-banana-farm pull request #21
Opened 2021-09-29 23:55 UTC by DeFiFoFum

The `MasterApeAdmin` contract is an admin helper proxy contract to the MasterApe which add the following functionality: 

- Add batch MasterApe farms
- Set batch MasterApe farms
- Add "Fixed Percentage Farms": These are farms that need to take a constant percentage of the newly minted BANANA supply. One use is to support "ghost farms" without needing to constantly update allocations. 
- Update/Remove "Fixed Percentage Farms": Change percentage allocations 

When new farms are added or updated through the `MasterApeAdmin` contract, the fixed percentage allocation farms are updated directly after to keep their percentages constant.

2021-10-08 17:10 UTC, Apegurus commented on contracts/MasterApeAdmin.sol
> +    function getDetailedPoolInfo(uint pid) external view returns (
Very nice helper function!

2021-10-08 17:14 UTC, Apegurus commented on contracts/MasterApeAdmin.sol
> +    function _syncFixedPercentFarms() internal {
Should we add the possibility to send a range to this function? 

Thus not bricking the contract if a gas limit is hit.

2021-10-08 17:20 UTC, Apegurus requested changes
Would be nice to add the possibility to send a range/array of PIDs to avoid the contract being bricked by gas limits

2021-10-12 18:10 UTC, DeFiFoFum commented on contracts/MasterApeAdmin.sol
> +    function _syncFixedPercentFarms() internal {
We can find ways to improve the gas efficiency, but the current calculation depends on updating them all at once.

Also, if this function doesn't work, it won't brick the contract as you can still make farm updates without syncing and we can remove fixed percentage farms if there are too many.

2021-10-13 17:08 UTC, Apegurus commented on contracts/MasterApeAdmin.sol
> +    function _syncFixedPercentFarms() internal {
Got it!

2021-10-13 21:32 UTC, ape-swap approved these changes

2021-11-23 14:38 UTC, merged